// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuBn6RAvDzfLRPEJiHife2x4ZJwFJ5788',
    appId: '1:648657833324:web:d8225cbf03f78e1fbd3749',
    messagingSenderId: '648657833324',
    projectId: 'byteboxapp',
    authDomain: 'byteboxapp.firebaseapp.com',
    storageBucket: 'byteboxapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDeSa-VznEeTRvqHErSL_T33HGNUPb8Ac',
    appId: '1:648657833324:android:914822243c9cb6a8bd3749',
    messagingSenderId: '648657833324',
    projectId: 'byteboxapp',
    storageBucket: 'byteboxapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd9KgQikjsj_wH5W6YZk-utxo3Rzg6Aow',
    appId: '1:648657833324:ios:61e0804c8f17b042bd3749',
    messagingSenderId: '648657833324',
    projectId: 'byteboxapp',
    storageBucket: 'byteboxapp.appspot.com',
    androidClientId: '648657833324-mhn0gqnerea0p4hnk7d6an3s4itjie99.apps.googleusercontent.com',
    iosClientId: '648657833324-p5n0ucpcqgv62f8ibn12b4m49jtkm78c.apps.googleusercontent.com',
    iosBundleId: 'com.example.byteBox',
  );
}
